### ISSUE TITLE
cloud['x'], cloud['y'], cloud['z'],cloud['nx'], cloud['ny'], cloud['nz'] 

### ISSUE THREAD

**Issue by WillingDil** [Xyouz/EdgeConvNpm3D#1]
thank you for your work! I learn a lot from it.but there is a issue when I run the following 

python3 main_seg.py --exp_name=seg --workers 6 --num_points=1024 --k=20  --tnet 1 --loss bce --epochs 10000

self.points = [np.vstack((cloud['x'], cloud['y'], cloud['z'],cloud['nx'], cloud['ny'], cloud['nz'])).T for cloud in clouds]
ValueError: no field of name nx

I download the dataset from here:[https://cloud.mines-paristech.fr/index.php/s/tQGOEIfHQCr22f9] and I find that the point data format is different from your data format in your code ,Can you give me some advice? thanks a lot

**Comment by Xyouz** [comment]
Hi,
I am glad you found it useful. The fields nx, ny, nz correspond to the normal direction of each point. This is not provided with the dataset but can easily be obtained. For instance, I used [CloudCompare](https://www.danielgm.net/cc/) : open the point cloud, go to Edit>Normals>Compute. You can then save the resulting point cloud in the .ply format using the binary option.

**Comment by WillingDil** [comment]
I am truely grateful for your help ! I try the steps as you say, it works ! Thank you so much

**Comment by WillingDil** [comment]
sorry to trouble you again,I face another problem
self.labels = [cloud['scalar_class'].astype(np.int64) - 1 for cloud in clouds]
ValueError: no field of name scalar_class
I used the CloudCompare: open the point cloud,go to Edit>Scalar fields>Add point indexes as SF
,however I get the scalar_Id, I can't get the scalar_class.
Any advice will be greatly appriciated !!!

**Comment by Xyouz** [comment]
I guess you forgot to tell cloudcompare to use the ```class``` field before computing the normals. When you open the file make sure the option window look like this:
![cloudcompare](https://user-images.githubusercontent.com/16564254/80300469-686fe400-879d-11ea-957c-9c23adb33162.png)
After clicking ```apply``` the point cloud visualization should color points based on their label.

Let me know if you have any other issue.

**Comment by WillingDil** [comment]
Thank you, It my fault that I used the test data file to get the scalar_class, only the train data file have that option. thank you for your time! Thanks a million !
